// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_cyberpunk_challenge_5;

#nullable disable

namespace dotnet_cyberpunk_challenge_5.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.AraskaDevice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("architecture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("athenaAccessKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("clusterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("processorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("publicKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("clusterId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.Cluster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("clusterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("creationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("kubernetesVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("memoryGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("storageTb")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.DataEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("appName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("appVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("deviceBrand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("deviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("deviceModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("errorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("errorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("eventTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("eventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ipAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("macAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("osVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("responseTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("userAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("deviceId");

                    b.ToTable("DataEvents");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.MemoryMapping", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("deviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("memoryEccSupport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memoryFormFacter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("memoryHeatSpreader")
                        .HasColumnType("INTEGER");

                    b.Property<int>("memoryLatency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("memorySizeGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("memorySpeedMhz")
                        .HasColumnType("INTEGER");

                    b.Property<string>("memoryTechnology")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("memoryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("memoryVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("memoryWarrantyYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("deviceId");

                    b.ToTable("MemoryMappings");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.Processes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("deviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("family")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("memory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("openFiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("deviceId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.AraskaDevice", b =>
                {
                    b.HasOne("dotnet_cyberpunk_challenge_5.Models.Cluster", "cluster")
                        .WithMany("devices")
                        .HasForeignKey("clusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cluster");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.DataEvent", b =>
                {
                    b.HasOne("dotnet_cyberpunk_challenge_5.Models.AraskaDevice", "device")
                        .WithMany("dataEvents")
                        .HasForeignKey("deviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("device");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.MemoryMapping", b =>
                {
                    b.HasOne("dotnet_cyberpunk_challenge_5.Models.AraskaDevice", "device")
                        .WithMany("memoryMappings")
                        .HasForeignKey("deviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("device");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.Processes", b =>
                {
                    b.HasOne("dotnet_cyberpunk_challenge_5.Models.AraskaDevice", "device")
                        .WithMany("processes")
                        .HasForeignKey("deviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("device");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.AraskaDevice", b =>
                {
                    b.Navigation("dataEvents");

                    b.Navigation("memoryMappings");

                    b.Navigation("processes");
                });

            modelBuilder.Entity("dotnet_cyberpunk_challenge_5.Models.Cluster", b =>
                {
                    b.Navigation("devices");
                });
#pragma warning restore 612, 618
        }
    }
}
